-- MySQL Script generated by MySQL Workbench
-- Mon Aug  4 17:44:11 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bestiario
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bestiario` ;

-- -----------------------------------------------------
-- Schema bestiario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bestiario` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bestiario` ;

-- -----------------------------------------------------
-- Table `bestiario`.`bestia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bestiario`.`bestia` ;

CREATE TABLE IF NOT EXISTS `bestiario`.`bestia` (
  `idBestia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `peligrosidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idBestia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `idbestia_UNIQUE` ON `bestiario`.`bestia` (`idBestia` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bestiario`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bestiario`.`categoria` ;

CREATE TABLE IF NOT EXISTS `bestiario`.`categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NOT NULL,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `idCategoria_UNIQUE` ON `bestiario`.`categoria` (`idCategoria` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bestiario`.`bestia_categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bestiario`.`bestia_categoria` ;

CREATE TABLE IF NOT EXISTS `bestiario`.`bestia_categoria` (
  `idBestia` INT NOT NULL,
  `idCategoria` INT NOT NULL,
  PRIMARY KEY (`idBestia`, `idCategoria`),
  CONSTRAINT `fk_bestia_bestia_categoria`
    FOREIGN KEY (`idBestia`)
    REFERENCES `bestiario`.`bestia` (`idBestia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_categoria_ bestia_categoria`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `bestiario`.`categoria` (`idCategoria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_categoria_ bestia_categoria_idx` ON `bestiario`.`bestia_categoria` (`idCategoria` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bestiario`.`habitat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bestiario`.`habitat` ;

CREATE TABLE IF NOT EXISTS `bestiario`.`habitat` (
  `idHabitat` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `localizacion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idHabitat`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `idhabitat_UNIQUE` ON `bestiario`.`habitat` (`idHabitat` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bestiario`.`bestia_habitat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bestiario`.`bestia_habitat` ;

CREATE TABLE IF NOT EXISTS `bestiario`.`bestia_habitat` (
  `idHabitat` INT NOT NULL,
  `idBestia` INT NOT NULL,
  PRIMARY KEY (`idHabitat`, `idBestia`),
  CONSTRAINT `fk_bestia_habitat_bestia`
    FOREIGN KEY (`idBestia`)
    REFERENCES `bestiario`.`bestia` (`idBestia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_bestia_habitat_habitat`
    FOREIGN KEY (`idHabitat`)
    REFERENCES `bestiario`.`habitat` (`idHabitat`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_bestia_habitat_bestia_idx` ON `bestiario`.`bestia_habitat` (`idBestia` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bestiario`.`caracteristicahabitat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bestiario`.`caracteristicahabitat` ;

CREATE TABLE IF NOT EXISTS `bestiario`.`caracteristicahabitat` (
  `descripcion` VARCHAR(255) NOT NULL,
  `idHabitat` INT NOT NULL,
  PRIMARY KEY (`descripcion`, `idHabitat`),
  CONSTRAINT `fk_caracteristicas_habitat`
    FOREIGN KEY (`idHabitat`)
    REFERENCES `bestiario`.`habitat` (`idHabitat`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_habitat` ON `bestiario`.`caracteristicahabitat` (`idHabitat` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bestiario`.`tipo_evidencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bestiario`.`tipo_evidencia` ;

CREATE TABLE IF NOT EXISTS `bestiario`.`tipo_evidencia` (
  `idTipoEvidencia` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idTipoEvidencia`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `idTipoEvidencia_UNIQUE` ON `bestiario`.`tipo_evidencia` (`idTipoEvidencia` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bestiario`.`evidencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bestiario`.`evidencia` ;

CREATE TABLE IF NOT EXISTS `bestiario`.`evidencia` (
  `nroEvidencia` INT NOT NULL,
  `fechaObtencion` DATE NOT NULL,
  `estado` VARCHAR(45) NOT NULL DEFAULT '"pendiente"',
  `link` VARCHAR(255) NULL DEFAULT NULL,
  `Evidenciacol` VARCHAR(45) NULL DEFAULT NULL,
  `idTipoEvidencia` INT NULL DEFAULT NULL,
  PRIMARY KEY (`nroEvidencia`),
  CONSTRAINT `idTipoEvidencia`
    FOREIGN KEY (`idTipoEvidencia`)
    REFERENCES `bestiario`.`tipo_evidencia` (`idTipoEvidencia`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `idEvidencia_UNIQUE` ON `bestiario`.`evidencia` (`nroEvidencia` ASC) VISIBLE;

CREATE INDEX `idTipoEvidencia_idx` ON `bestiario`.`evidencia` (`idTipoEvidencia` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bestiario`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bestiario`.`usuario` ;

CREATE TABLE IF NOT EXISTS `bestiario`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(255) NOT NULL,
  `contraseña` VARCHAR(255) NOT NULL,
  `esInvestigador` TINYINT NOT NULL DEFAULT '0',
  `fechaNacimiento` DATE NULL DEFAULT NULL,
  `nombre` VARCHAR(50) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `dni` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `correo_UNIQUE` ON `bestiario`.`usuario` (`correo` ASC) VISIBLE;

CREATE UNIQUE INDEX `idUsuario_UNIQUE` ON `bestiario`.`usuario` (`idUsuario` ASC) VISIBLE;

CREATE UNIQUE INDEX `dni_UNIQUE` ON `bestiario`.`usuario` (`dni` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bestiario`.`noticia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bestiario`.`noticia` ;

CREATE TABLE IF NOT EXISTS `bestiario`.`noticia` (
  `idNoticia` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL DEFAULT 'pendiente',
  `fechaPublicacion` DATE NULL DEFAULT NULL,
  `idUsuario` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idNoticia`),
  CONSTRAINT `fk_noticia_usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `bestiario`.`usuario` (`idUsuario`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_noticia_usuario` ON `bestiario`.`noticia` (`idUsuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bestiario`.`registro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bestiario`.`registro` ;

CREATE TABLE IF NOT EXISTS `bestiario`.`registro` (
  `nroRegistro` INT NOT NULL,
  `detalles` LONGTEXT NULL DEFAULT NULL,
  `fechaAprobacion` DATE NULL DEFAULT NULL,
  `fechaBaja` DATE NULL DEFAULT NULL,
  `idUsuario` INT NULL DEFAULT NULL,
  `estado` VARCHAR(45) NOT NULL DEFAULT '"pendiente"',
  `idBestia` INT NOT NULL,
  PRIMARY KEY (`nroRegistro`),
  CONSTRAINT `idBestia`
    FOREIGN KEY (`idBestia`)
    REFERENCES `bestiario`.`bestia` (`idBestia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `bestiario`.`usuario` (`idUsuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `nroRegistro_UNIQUE` ON `bestiario`.`registro` (`nroRegistro` ASC) VISIBLE;

CREATE INDEX `idUsuario_idx` ON `bestiario`.`registro` (`idUsuario` ASC) VISIBLE;

CREATE INDEX `idBestia_idx` ON `bestiario`.`registro` (`idBestia` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
